# Generated by Django 2.2.5 on 2021-02-08 04:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departmentID', models.CharField(max_length=5, verbose_name='部門コード')),
                ('taskID', models.CharField(max_length=5, verbose_name='タスクコード')),
                ('TargetMonth', models.CharField(max_length=6, verbose_name='対象年月')),
                ('toDoFlg', models.BooleanField(default=False, verbose_name='実行状況')),
            ],
            options={
                'db_table': 'ExState',
            },
        ),
    ]
