# Generated by Django 2.2.5 on 2021-02-09 03:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MasterData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TargetMonth', models.CharField(max_length=6, verbose_name='対象年月')),
                ('toDoFlg', models.BooleanField(default=False, verbose_name='実行状況')),
                ('depart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MasterData.DeptsMaster', verbose_name='部署')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MasterData.TasksMaster', verbose_name='タスク名')),
            ],
            options={
                'db_table': 'ExState',
            },
        ),
    ]
